<?php
/**
 * TL_ROOT/system/modules/mailusername/languages/it/default.php 
 * 
 * Contao extension: mailusername 1.0.2 stable 
 * Italian translation file 
 * 
 * Copyright : © 2009-2011 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Andrea Bizioli (Abisem) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['username'] = "Indirizzo e-mail";
 
?>
